config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
resources :books do
  resources :reviews
end

  root "books#index"

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :category
  belongs_to :admin
  has_many :reviews

  has_attached_file :book_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :books
  belongs_to :admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :find_book, only:[:show, :edit, :update, :destroy]


  def index
    if params[:category].blank?
      @books = Book.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @books = Book.where(:category_id => @category_id).order("created_at DESC")
    end
  end

  def new
    @book = Book.new
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def show

  end

  def create
    @book = Book.new(book_params)
    @book.category_id = params[:category_id]
      if @book.save
        redirect_to root_path
      else
        render 'new'
      end
  end

  def edit
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def update
    @book.category_id = params[:category_id]
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
      redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :description, :category_id, :book_img)
  end


  def find_book
    @book = Book.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :find_book
before_action :find_review, only: [:edit, :update, :destroy]

  def new
    @review = Review.new

  end

  def create
    @review = Review.new(review_params)

    @review.book_id = @book.id
    @review.admin_id = current_admin.id

      if @review.save
        redirect_to book_path(@book)
      else
        render 'new'
    end
  end

  def edit

  end

  def update

      if @review.update(review_params)
        redirect_to book_path(@book)
      else
        render 'edit'
      end
  end

  def destroy
    @review.destroy
      redirect_to book_path(@book)
  end

private

  def find_book
    @book = Book.find(params[:book_id])
  end

  def review_params
    params.require(:review).permit(:comment, :rating)
  end

  def find_review
    @review = Review.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select Category") %>
  <%= f.file_field :book_img %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :description, as: :text %>
  <%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<h2>Edit page</h2>

<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
  <%= f.select :category_id, @categories %>
  <%= f.file_field :book_img %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :description, as: :text %>
  <%= f.button :submit %>
<% end %>

app/views/books/index.html.erb
<h2>Index page</h2>

<h2 class="current-category"><%= params[:category] %></h2>
  <% if @books.count == 0 %>
<h3>There are currently no books in this category</h3>

  <% else %>

<div class="row">

  <% @books.each do |book| %>
    <div class="col-md-3">
      <a href="/books/<%= book.id %>">
      <%= image_tag book.book_img.url(:book_index), class: "book" %></a>
    </div>
      <% end %>

</div>

<% end %>

app/views/books/new.html.erb
<h2>New page</h2>

<%= render 'form' %>

app/views/books/show.html.erb
<h2>Show page</h2>

<div class="row">
  <div class="col-md-4">
    <%= image_tag @book.book_img.url(:book_show), class: "book_show" %>
  </div>


  <div class="col-md-8">
    <h2><%= @book.title %></h2>
    <h3><%= @book.author %></h3>
    <p><%= @book.description %></p>
  </div>
</div>


<div class="row">
  <div class="col-md-4">

    <%= render @book.reviews %>

      <div>
        <%= link_to "Add Review", new_book_review_path(@book) %>
      </div>

  </div>
</div>

  <% if admin_signed_in? %>
    <% if @book.admin_id == current_admin.id %>

  <%= link_to "Edit", edit_book_path(@book) %>

  <%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are You SURE ?" } %>

  <% end %>
<% end %>

  <% else %>

  <%= link_to "Back", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookRev</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "BookReview", root_path, class: "navbar-brand" %>
      </div>

      <ul class="nav navbar-nav">

          <% if admin_signed_in? %>

        <li><%= link_to "Sign out", destroy_admin_session_path, method: :delete %></li>

         <% else %>

         <li><%= link_to "Sign up", new_admin_registration_path %></li>

        <li><%= link_to "Log in", new_admin_session_path %></li>

          <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |category| %>
            <li class="<%= 'active' if params[:category] == category.name %>">
              <%= link_to category.name, books_path(category: category.name), class: "link" %>
            </li>
            <% end %>
          </ul>
        </li>

        <% if admin_signed_in? %>
          <li><%= link_to "Add book", new_book_path %></li>
        <% end %>
      </ul>

    </div>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

 <div class="container">
    <%= yield %>
 </div>

  </body>
</html>

app/views/reviews/_form.html.erb
<h2>Review form</h2>

<%= simple_form_for([@book, @book.reviews.build]) do |f| %>
  <%= f.input :rating %>
  <%= f.input :comment %>
  <%= f.button :submit %>

<% end %>

app/views/reviews/_review.html.erb
<p><%= review.rating %></p>
<p><%= review.comment %></p>

<% if admin_signed_in? %>
<% if review.admin_id == current_admin.id %>

<%= link_to "Edit", edit_book_review_path(review.book, review) %>

<%= link_to "Delete", book_review_path(review.book, review), method: :delete, data: { confirm: "Are you SURE ?" } %>

<% end %>
<% end %>

app/views/reviews/edit.html.erb
<h2>Edit Review</h2>

<%= simple_form_for([@book, @review]) do |f| %>
  <%= f.input :rating %>
  <%= f.input :comment %>
  <%= f.button :submit %>

<% end %>

app/views/reviews/new.html.erb
<h2>New Review</h2>

<%= render 'form' %>